# Generated by Django 5.1 on 2025-05-15 19:12

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fsm', '0250_alter_registrationreceipt_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(editable=False, help_text='Unique identifier for the meeting', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('title', models.CharField(help_text='Short meeting title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed meeting description')),
                ('creator', models.UUIDField()),
                ('start_time', models.DateTimeField(help_text='Date and time when the meeting starts')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=4500), help_text='Length of the meeting as a duration', validators=[django.core.validators.MinValueValidator(limit_value=datetime.timedelta(seconds=60))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('ended', 'Ended'), ('canceled', 'Canceled')], default='scheduled', max_length=20)),
                ('location_type', models.CharField(choices=[('online', 'Online'), ('physical', 'Physical'), ('hybrid', 'Hybrid')], default='online', max_length=20)),
                ('recording_url', models.URLField(blank=True, help_text='URL for meeting recording', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='fsm.program')),
            ],
            options={
                'permissions': [('can_schedule_meeting', 'Can schedule meetings'), ('can_cancel_meeting', 'Can cancel meetings')],
                'indexes': [models.Index(fields=['start_time'], name='meeting_mee_start_t_b59151_idx'), models.Index(fields=['status'], name='meeting_mee_status_83da76_idx')],
            },
        ),
    ]
