# Generated by Django 5.1 on 2025-05-12 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(help_text='Unique identifier for the meeting', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('title', models.CharField(help_text='Short meeting title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed meeting description')),
                ('program', models.IntegerField()),
                ('creator', models.UUIDField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('ended', 'Ended'), ('canceled', 'Canceled')], default='scheduled', max_length=20)),
                ('location_type', models.CharField(choices=[('online', 'Online'), ('physical', 'Physical'), ('hybrid', 'Hybrid')], default='online', max_length=20)),
                ('recording_url', models.URLField(blank=True, help_text='URL for meeting recording', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_time'],
                'permissions': [('can_schedule_meeting', 'Can schedule meetings'), ('can_cancel_meeting', 'Can cancel meetings')],
                'indexes': [models.Index(fields=['start_time', 'end_time'], name='meeting_mee_start_t_6ebfbd_idx'), models.Index(fields=['status'], name='meeting_mee_status_83da76_idx')],
            },
        ),
    ]
