# Generated by Django 5.1 on 2025-05-12 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0250_alter_registrationreceipt_options_and_more'),
        ('meeting', '0002_alter_meeting_options_alter_meeting_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='fsm.program'),
        ),
    ]
