# Generated by Django 5.2.1 on 2025-05-14 17:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0250_alter_registrationreceipt_options_and_more'),
        ('meeting', '0003_alter_meeting_program'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='meeting',
            name='meeting_mee_start_t_6ebfbd_idx',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='end_time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=4500), help_text='Length of the meeting as a duration', validators=[django.core.validators.MinValueValidator(limit_value=datetime.timedelta(seconds=60))]),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(help_text='Date and time when the meeting starts'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['start_time'], name='meeting_mee_start_t_b59151_idx'),
        ),
    ]
