# Generated by Django 5.1 on 2025-05-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_fix_start_time_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
