# Generated by Django 4.1.3 on 2024-09-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0015_alter_transaction_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cost',
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to',
        ),
        migrations.DeleteModel(
            name='ScoreType',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
