# Generated by Django 4.1.3 on 2024-10-07 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0193_alter_widget_widget_type'),
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fsm.widget')),
                ('label', models.TextField(default='')),
                ('background_image', models.URLField(blank=True, null=True)),
                ('destination_page_url', models.URLField(blank=True, null=True)),
                ('destination_state_ids', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('fsm.widget',),
        ),
        migrations.CreateModel(
            name='CustomWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fsm.widget')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('fsm.widget',),
        ),
    ]
