# Generated by Django 4.1.3 on 2024-10-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0003_rename_destination_state_ids_buttonwidget_edges_to_destination_states_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buttonwidget',
            name='edges_to_destination_states',
        ),
        migrations.AddField(
            model_name='buttonwidget',
            name='destination_states',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
