# Generated by Django 4.1.3 on 2024-11-17 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0232_alter_widget_widget_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('widgets', '0005_randomwidget_delete_customwidget'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomwidget',
            name='unique_widgets_only',
            field=models.BooleanField(default=False, help_text='If True, shows only unseen widgets. If False, shows any random widget.'),
        ),
        migrations.CreateModel(
            name='SeenWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('container_random_widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_seen_widget_records', to='widgets.randomwidget')),
                ('target_widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_widget_records', to='fsm.widget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_widget_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='seenwidget',
            index=models.Index(fields=['user', 'target_widget', 'container_random_widget'], name='widgets_see_user_id_bb79cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seenwidget',
            unique_together={('user', 'target_widget', 'container_random_widget')},
        ),
    ]
