# Generated by Django 4.1.3 on 2024-11-17 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fsm', '0232_alter_widget_widget_type'),
        ('widgets', '0006_randomwidget_unique_widgets_only_seenwidget_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='seenwidget',
            name='widgets_see_user_id_bb79cc_idx',
        ),
        migrations.AlterUniqueTogether(
            name='seenwidget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='seenwidget',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seen_widget_records', to='fsm.player'),
        ),
        migrations.AlterUniqueTogether(
            name='seenwidget',
            unique_together={('user', 'player', 'target_widget', 'container_random_widget')},
        ),
        migrations.AddIndex(
            model_name='seenwidget',
            index=models.Index(fields=['user', 'player', 'target_widget', 'container_random_widget'], name='widgets_see_user_id_fcd409_idx'),
        ),
    ]
