# Generated by Django 4.1.3 on 2024-11-17 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0232_alter_widget_widget_type'),
        ('widgets', '0007_remove_seenwidget_widgets_see_user_id_bb79cc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seenwidget',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_widget_records', to='fsm.player'),
        ),
    ]
