# Generated by Django 4.1.3 on 2025-02-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0008_alter_seenwidget_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttonwidget',
            name='disable_ripple',
            field=models.BooleanField(default=True),
        ),
    ]
