# Generated by Django 4.1.3 on 2025-02-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0009_buttonwidget_disable_ripple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buttonwidget',
            name='disable_ripple',
        ),
        migrations.AddField(
            model_name='buttonwidget',
            name='has_hover_effect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buttonwidget',
            name='has_ripple_on_click',
            field=models.BooleanField(default=False),
        ),
    ]
