# Generated by Django 5.1 on 2025-04-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0244_fsm_show_player_performance_on_end'),
        ('widgets', '0011_seenwidget_user2'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='seenwidget',
            name='widgets_see_user_id_fcd409_idx',
        ),
        migrations.AlterUniqueTogether(
            name='seenwidget',
            unique_together={('user2', 'player', 'target_widget', 'container_random_widget')},
        ),
        migrations.AddIndex(
            model_name='seenwidget',
            index=models.Index(fields=['user2', 'player', 'target_widget', 'container_random_widget'], name='widgets_see_user2_66f527_idx'),
        ),
        migrations.RemoveField(
            model_name='seenwidget',
            name='user',
        ),
    ]
