# Generated by Django 5.1 on 2025-04-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0244_fsm_show_player_performance_on_end'),
        ('widgets', '0012_remove_seenwidget_widgets_see_user_id_fcd409_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='seenwidget',
            name='widgets_see_user2_66f527_idx',
        ),
        migrations.RenameField(
            model_name='seenwidget',
            old_name='user2',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='seenwidget',
            unique_together={('user', 'player', 'target_widget', 'container_random_widget')},
        ),
        migrations.AddIndex(
            model_name='seenwidget',
            index=models.Index(fields=['user', 'player', 'target_widget', 'container_random_widget'], name='widgets_see_user_8a7b5f_idx'),
        ),
    ]
