# Generated by Django 5.1 on 2025-05-18 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0013_remove_seenwidget_widgets_see_user2_66f527_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buttonwidget',
            old_name='has_hover_effect',
            new_name='has_wave_effect',
        ),
    ]
