# Generated by Django 4.1.3 on 2024-03-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='verification_type',
            field=models.CharField(choices=[('change-user-password', 'Changeuserpassword'), ('register-user', 'Registeruser')], max_length=30, null=True),
        ),
    ]
