# Generated by Django 4.1.3 on 2024-03-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_verificationcode_verification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='verification_type',
            field=models.CharField(choices=[('create-user-account', 'Createuseraccount'), ('change-user-password', 'Changeuserpassword'), ('change-user-phone-number', 'Changeuserphonenumber')], max_length=30, null=True),
        ),
    ]
