# Generated by Django 4.1.3 on 2024-05-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_purchase_callback_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='is_event_owner',
            new_name='is_program_owner',
        ),
    ]
