# Generated by Django 4.1.3 on 2024-06-10 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_userwebsite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userwebsite',
            unique_together={('user', 'website')},
        ),
    ]
