# Generated by Django 4.1.3 on 2024-08-02 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_is_artificial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWebsiteLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('user_website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userwebsite')),
            ],
        ),
    ]
