# Generated by Django 4.1.3 on 2024-08-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_userwebsitelogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
