# Generated by Django 4.1.3 on 2024-08-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_user_profile_picture2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture2',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
