# Generated by Django 4.1.3 on 2024-08-08 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0148_remove_fsm_merchandise_remove_program_merchandise'),
        ('accounts', '0027_rename_profile_picture2_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchandise', to='fsm.program'),
        ),
    ]
