# Generated by Django 4.1.3 on 2024-08-08 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0148_remove_fsm_merchandise_remove_program_merchandise'),
        ('accounts', '0028_merchandise_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchandises', to='fsm.program'),
        ),
    ]
