# Generated by Django 4.1.3 on 2024-08-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_merchandise_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='discounted_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='price',
            field=models.IntegerField(),
        ),
    ]
