# Generated by Django 4.1.3 on 2024-08-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_rename_merchandise2_discountcode_merchandises'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
