# Generated by Django 4.1.3 on 2024-08-11 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_studentship_document2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentship',
            name='document',
        ),
    ]
