# Generated by Django 4.1.3 on 2024-08-11 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_remove_studentship_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentship',
            old_name='document2',
            new_name='document',
        ),
    ]
