# Generated by Django 4.1.3 on 2024-08-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_rename_document2_studentship_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='discount_code_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
