# Generated by Django 4.1.3 on 2024-10-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_delete_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
