# Generated by Django 4.1.3 on 2024-11-12 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_rename_profile_picture_user_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_artificial',
            new_name='is_temporary',
        ),
    ]
