# Generated by Django 4.1.3 on 2024-11-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_rename_is_artificial_user_is_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='origin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
