# Generated by Django 4.1.3 on 2024-12-20 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_user_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='accounts.discountcode'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='merchandise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='accounts.merchandise'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='accounts.voucher'),
        ),
    ]
