# Generated by Django 5.1 on 2025-02-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_alter_verificationcode_verification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentship',
            name='studentship_type',
            field=models.CharField(choices=[('School', 'School'), ('Academic', 'Academic')], max_length=100),
        ),
    ]
