# Generated by Django 5.1 on 2025-05-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwebsite',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
