# Generated by Django 5.1 on 2025-06-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_alter_userwebsite_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountcode',
            old_name='discount_code_limit',
            new_name='max_discount_amount',
        ),
    ]
