# Generated by Django 5.1 on 2025-06-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_rename_discount_code_limit_discountcode_max_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='remaining',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='NULL means unlimited uses', null=True),
        ),
    ]
