# Generated by Django 5.1 on 2025-06-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_alter_discountcode_remaining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='voucher',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
