# Generated by Django 4.1.3 on 2024-08-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Excel_Export_Date',
        ),
    ]
