# Generated by Django 3.1 on 2022-05-02 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0051_remove_event_crispwebsiteid'),
    ]

    operations = [
    ]
