# Generated by Django 3.1 on 2022-05-06 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0052_paper_criteria'),
    ]

    operations = [
    ]
