# Generated by Django 4.1.3 on 2024-01-05 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0088_remove_paper_criteria'),
    ]

    operations = [

    ]
