# Generated by Django 4.1.3 on 2024-03-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0094_article_party_event_party_fsm_party'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-id']},
        ),
    ]
