# Generated by Django 4.1.3 on 2024-04-18 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0098_fsm_cover_page2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fsm',
            name='cover_page',
        ),
    ]
