# Generated by Django 4.1.3 on 2024-04-18 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0099_remove_fsm_cover_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fsm',
            old_name='cover_page2',
            new_name='cover_page',
        ),
    ]
