# Generated by Django 4.1.3 on 2024-04-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0100_rename_cover_page2_fsm_cover_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsm',
            name='cover_page',
            field=models.URLField(default=''),
        ),
    ]
