# Generated by Django 4.1.3 on 2024-04-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0101_alter_fsm_cover_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsm',
            name='cover_page',
            field=models.URLField(),
        ),
    ]
