# Generated by Django 4.1.3 on 2024-04-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0102_alter_fsm_cover_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsm',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
