# Generated by Django 4.1.3 on 2024-04-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0103_fsm_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='party',
        ),
        migrations.RemoveField(
            model_name='event',
            name='party',
        ),
        migrations.RemoveField(
            model_name='fsm',
            name='party',
        ),
        migrations.AddField(
            model_name='article',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fsm',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
