# Generated by Django 4.1.3 on 2024-04-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0104_remove_article_party_remove_event_party_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_page2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
