# Generated by Django 4.1.3 on 2024-04-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0105_event_cover_page2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cover_page',
        ),
    ]
