# Generated by Django 4.1.3 on 2024-04-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0106_remove_event_cover_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='cover_page2',
            new_name='cover_page',
        ),
    ]
