# Generated by Django 4.1.3 on 2024-04-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0107_rename_cover_page2_event_cover_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
