# Generated by Django 4.1.3 on 2024-04-29 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0108_event_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programcontactinfo',
            name='name',
        ),
        migrations.AlterField(
            model_name='event',
            name='program_contact_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program', to='fsm.programcontactinfo'),
        ),
    ]
