# Generated by Django 4.1.3 on 2024-04-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0109_remove_programcontactinfo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='team_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
