# Generated by Django 4.1.3 on 2024-04-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0110_alter_event_team_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='has_certificate',
            field=models.BooleanField(default=False),
        ),
    ]
