# Generated by Django 4.1.3 on 2024-05-11 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0111_alter_registrationform_has_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerhistory',
            old_name='reverse_enter',
            new_name='is_edge_passed_in_reverse',
        ),
        migrations.AlterField(
            model_name='playerhistory',
            name='entered_by_edge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players_histories', to='fsm.edge'),
        ),
        migrations.AlterField(
            model_name='playerhistory',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players_histories', to='fsm.state'),
        ),
    ]
