# Generated by Django 4.1.3 on 2024-05-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0112_rename_reverse_enter_playerhistory_is_edge_passed_in_reverse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerhistory',
            old_name='entered_by_edge',
            new_name='passed_edge',
        ),
        migrations.AlterField(
            model_name='playerhistory',
            name='is_edge_passed_in_reverse',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
