# Generated by Django 4.1.3 on 2024-05-13 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0113_rename_entered_by_edge_playerhistory_passed_edge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerhistory',
            old_name='is_edge_passed_in_reverse',
            new_name='is_edge_transited_in_reverse',
        ),
        migrations.RenameField(
            model_name='playerhistory',
            old_name='passed_edge',
            new_name='transited_edge',
        ),
        migrations.AddField(
            model_name='playerhistory',
            name='source_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_of_players_transitions', to='fsm.state'),
        ),
        migrations.AlterField(
            model_name='playerhistory',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_of_players_transitions', to='fsm.state'),
        ),
    ]
