# Generated by Django 4.1.3 on 2024-05-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0114_rename_is_edge_passed_in_reverse_playerhistory_is_edge_transited_in_reverse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerhistory',
            old_name='state',
            new_name='target_state',
        ),
    ]
