# Generated by Django 4.1.3 on 2024-05-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0115_rename_state_playerhistory_target_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerhistory',
            name='is_edge_transited_in_reverse',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
