# Generated by Django 4.1.3 on 2024-05-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0116_alter_playerhistory_is_edge_transited_in_reverse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerhistory',
            old_name='target_state',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='playerhistory',
            name='source_state',
        ),
    ]
