# Generated by Django 4.1.3 on 2024-05-13 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0118_rename_playerhistory_playerstatehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatehistory',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstatehistory',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='playerstatehistory',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_state_histories', to='fsm.state'),
        ),
        migrations.AlterField(
            model_name='playerstatehistory',
            name='transited_edge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_histories', to='fsm.edge'),
        ),
    ]
