# Generated by Django 4.1.3 on 2024-05-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0120_playertransitionhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerstatehistory',
            old_name='start_time',
            new_name='arrival_time',
        ),
        migrations.RenameField(
            model_name='playerstatehistory',
            old_name='end_time',
            new_name='departure_time',
        ),
    ]
