# Generated by Django 4.1.3 on 2024-05-13 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0121_rename_start_time_playerstatehistory_arrival_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerTransitionHistory',
            new_name='PlayerTransition',
        ),
        migrations.AddField(
            model_name='playerstatehistory',
            name='arrival',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_arrival_history', to='fsm.playertransition'),
        ),
        migrations.AddField(
            model_name='playerstatehistory',
            name='departure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_departure_history', to='fsm.playertransition'),
        ),
    ]
