# Generated by Django 4.1.3 on 2024-05-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0122_rename_playertransitionhistory_playertransition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playertransition',
            name='is_edge_transited_in_reverse',
        ),
        migrations.AlterField(
            model_name='playerstatehistory',
            name='arrival_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='playertransition',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
