# Generated by Django 4.1.3 on 2024-05-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0123_remove_playertransition_is_edge_transited_in_reverse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatehistory',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
