# Generated by Django 4.1.3 on 2024-05-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0124_playerstatehistory_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertransition',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
