# Generated by Django 4.1.3 on 2024-05-15 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0125_alter_playertransition_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatehistory',
            name='is_processed2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playertransition',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_transitions', to='fsm.player'),
        ),
        migrations.AlterField(
            model_name='playerstatehistory',
            name='arrival',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_target_state_history', to='fsm.playertransition'),
        ),
        migrations.AlterField(
            model_name='playerstatehistory',
            name='departure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_source_state_history', to='fsm.playertransition'),
        ),
        migrations.AlterField(
            model_name='playerstatehistory',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_state_histories', to='fsm.player'),
        ),
        migrations.AlterField(
            model_name='playertransition',
            name='source_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_departure_transitions', to='fsm.state'),
        ),
        migrations.AlterField(
            model_name='playertransition',
            name='target_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_arrival_transitions', to='fsm.state'),
        ),
        migrations.AlterField(
            model_name='playertransition',
            name='transited_edge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_transitions', to='fsm.edge'),
        ),
    ]
