# Generated by Django 4.1.3 on 2024-05-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0126_playerstatehistory_is_processed2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fsm',
            name='holder',
        ),
    ]
