# Generated by Django 4.1.3 on 2024-05-21 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rename_is_event_owner_member_is_program_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fsm', '0127_remove_fsm_holder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_type',
            new_name='program_type',
        ),
        migrations.RenameField(
            model_name='fsm',
            old_name='event',
            new_name='program',
        ),
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='accounts.educationalinstitute'),
        ),
        migrations.AlterField(
            model_name='event',
            name='merchandise',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program', to='accounts.merchandise'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_form',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program', to='fsm.registrationform'),
        ),
    ]
