# Generated by Django 4.1.3 on 2024-05-21 14:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0019_rename_is_event_owner_member_is_program_owner'),
        ('fsm', '0128_rename_event_type_event_program_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Program',
        ),
    ]
