# Generated by Django 4.1.3 on 2024-05-21 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fsm', '0129_rename_event_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='admins',
            field=models.ManyToManyField(blank=True, null=True, related_name='administered_programs', to=settings.AUTH_USER_MODEL),
        ),
    ]
