# Generated by Django 4.1.3 on 2024-05-24 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fsm', '0130_program_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationreceipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_receipts', to=settings.AUTH_USER_MODEL),
        ),
    ]
