# Generated by Django 4.1.3 on 2024-05-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0131_alter_registrationreceipt_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerWorkshop',
        ),
    ]
