# Generated by Django 4.1.3 on 2024-05-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0132_delete_playerworkshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsm',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
