# Generated by Django 4.1.3 on 2024-05-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0133_fsm_is_deleted_program_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsm',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
