# Generated by Django 4.1.3 on 2024-06-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0136_remove_playerstatehistory_arrival_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multichoiceproblem',
            old_name='max_choices',
            new_name='maximum_choices_could_be_chosen',
        ),
    ]
