# Generated by Django 4.1.3 on 2024-07-07 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0137_rename_max_choices_multichoiceproblem_maximum_choices_could_be_chosen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='program',
            name='is_private',
        ),
        migrations.AlterField(
            model_name='program',
            name='registration_form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='program', to='fsm.registrationform'),
        ),
    ]
