# Generated by Django 4.1.3 on 2024-07-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0138_remove_article_is_private_remove_program_is_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfileanswer',
            name='answer_file2',
            field=models.URLField(blank=True),
        ),
    ]
