# Generated by Django 4.1.3 on 2024-07-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0139_uploadfileanswer_answer_file2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfileanswer',
            name='answer_file2',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
