# Generated by Django 4.1.3 on 2024-07-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0141_remove_uploadfileanswer_answer_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfileanswer',
            old_name='answer_file2',
            new_name='answer_file',
        ),
    ]
