# Generated by Django 4.1.3 on 2024-07-26 22:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fsm', '0142_rename_answer_file2_uploadfileanswer_answer_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationreceipt',
            old_name='answer_sheet_of',
            new_name='form',
        ),
        migrations.AlterUniqueTogether(
            name='registrationreceipt',
            unique_together={('form', 'user')},
        ),
    ]
