# Generated by Django 4.1.3 on 2024-07-28 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0143_rename_answer_sheet_of_registrationreceipt_form_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='required',
            new_name='is_required',
        ),
    ]
