# Generated by Django 4.1.3 on 2024-07-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0144_rename_required_problem_is_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='be_corrected',
        ),
        migrations.AddField(
            model_name='problem',
            name='be_corrected',
            field=models.BooleanField(default=False),
        ),
    ]
