# Generated by Django 4.1.3 on 2024-07-28 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0145_remove_widget_be_corrected_problem_be_corrected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationreceipt',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_receipts', to='fsm.registrationform'),
        ),
    ]
