# Generated by Django 4.1.3 on 2024-08-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_alter_intrinsicattribute_type_and_more'),
        ('fsm', '0148_remove_fsm_merchandise_remove_program_merchandise'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsm',
            name='attributes',
            field=models.ManyToManyField(blank=True, null=True, to='attributes.attribute'),
        ),
    ]
