# Generated by Django 4.1.3 on 2024-08-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0003_alter_intrinsicattribute_type_and_more'),
        ('fsm', '0149_fsm_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='has_lock',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='lock',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='min_score',
        ),
        migrations.RemoveField(
            model_name='fsm',
            name='lock',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='reward',
        ),
        migrations.AddField(
            model_name='edge',
            name='attributes',
            field=models.ManyToManyField(blank=True, null=True, to='attributes.attribute'),
        ),
    ]
