# Generated by Django 4.1.3 on 2024-08-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0003_alter_intrinsicattribute_type_and_more'),
        ('fsm', '0150_remove_edge_cost_remove_edge_has_lock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='attributes',
            field=models.ManyToManyField(blank=True, null=True, to='attributes.attribute'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('Iframe', 'Iframe'), ('Video', 'Video'), ('Image', 'Image'), ('Aparat', 'Aparat'), ('Audio', 'Audio'), ('TextWidget', 'Textwidget'), ('DetailBoxWidget', 'Detailboxwidget'), ('SmallAnswerProblem', 'Smallanswerproblem'), ('BigAnswerProblem', 'Biganswerproblem'), ('MultiChoiceProblem', 'Multichoiceproblem'), ('UploadFileProblem', 'Uploadfileproblem')], max_length=30),
        ),
    ]
