# Generated by Django 4.1.3 on 2024-08-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0153_widget_is_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widget',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='widget',
            order_with_respect_to=None,
        ),
    ]
