# Generated by Django 4.1.3 on 2024-08-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0154_alter_widget_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique identifier for the program', max_length=100, null=True, unique=True),
        ),
    ]
