# Generated by Django 4.1.3 on 2024-08-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0155_program_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='program_type',
            new_name='participation_type',
        ),
        migrations.AddField(
            model_name='program',
            name='type',
            field=models.CharField(choices=[('Event', 'Event'), ('Class', 'Class'), ('Campaign', 'Campaign'), ('Game', 'Game'), ('Course', 'Course')], default='Event', max_length=40),
        ),
    ]
