# Generated by Django 4.1.3 on 2024-09-02 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0158_fsm_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='fsm.program'),
        ),
    ]
