# Generated by Django 4.1.3 on 2024-09-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0159_team_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='registration_form',
        ),
    ]
