# Generated by Django 4.1.3 on 2024-09-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0161_alter_team_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='template',
            field=models.CharField(choices=[('normal', 'Normal'), ('board', 'Board')], default='normal', max_length=20),
        ),
    ]
