# Generated by Django 4.1.3 on 2024-09-05 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0162_state_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetPosition',
            fields=[
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fsm.widget')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
    ]
