# Generated by Django 4.1.3 on 2024-09-09 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('attributes', '0004_alter_performableaction_type'),
        ('fsm', '0163_widgetposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('_attributes', models.ManyToManyField(blank=True, null=True, to='attributes.attribute')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.RemoveField(
            model_name='edge',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='fsm',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='attributes',
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='_position', serialize=False, to='fsm.object')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='WidgetPosition',
        ),
        migrations.AddField(
            model_name='edge',
            name='_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edge', to='fsm.object'),
        ),
        migrations.AddField(
            model_name='fsm',
            name='_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fsm', to='fsm.object'),
        ),
        migrations.AddField(
            model_name='paper',
            name='_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper', to='fsm.object'),
        ),
        migrations.AddField(
            model_name='widget',
            name='_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widget', to='fsm.object'),
        ),
    ]
