# Generated by Django 4.1.3 on 2024-09-09 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0164_object_remove_edge_attributes_remove_fsm_attributes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='_attributes',
            new_name='attributes',
        ),
        migrations.AlterField(
            model_name='position',
            name='object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='position', serialize=False, to='fsm.object'),
        ),
    ]
