# Generated by Django 4.1.3 on 2024-09-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0166_state_show_appbar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='is_exam',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='since',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='till',
        ),
        migrations.AddField(
            model_name='registrationform',
            name='since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
