# Generated by Django 4.1.3 on 2024-09-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0167_remove_paper_duration_remove_paper_is_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsm',
            name='card_type',
            field=models.CharField(choices=[('vertical1', 'Vertical1'), ('horizontal1', 'Horizontal1')], default='vertical1', max_length=20),
        ),
        migrations.AddField(
            model_name='fsm',
            name='show_roadmap',
            field=models.BooleanField(default=True),
        ),
    ]
