# Generated by Django 4.1.3 on 2024-09-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0168_fsm_card_type_fsm_show_roadmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='is_end',
            field=models.BooleanField(default=False),
        ),
    ]
