# Generated by Django 4.1.3 on 2024-09-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0171_remove_state_template_paper_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='object',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
