# Generated by Django 4.1.3 on 2024-09-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0174_alter_registrationreceipt_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationreceipt',
            name='form',
        ),
        migrations.RenameField(
            model_name='answersheet',
            old_name='form2',
            new_name='form',
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='answer_sheet_type',
            field=models.CharField(choices=[('RegistrationReceipt', 'Registrationreceipt'), (
                'StateAnswerSheet', 'Stateanswersheet'), ('General', 'General')], default='General', max_length=25),
        ),
    ]
