# Generated by Django 4.1.3 on 2024-09-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0176_form_registrationform2_program_registration_form2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='registration_form2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program', to='fsm.registrationform2'),
        ),
    ]
