# Generated by Django 4.1.3 on 2024-09-25 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0178_answersheet_form2'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='registration_form2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='fsm.registrationform2'),
        ),
    ]
