# Generated by Django 4.1.3 on 2024-09-26 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0182_remove_fsm_registration_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersheet',
            name='formc',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='registration_formc',
        ),
        migrations.RemoveField(
            model_name='program',
            name='registration_formc',
        ),
        migrations.DeleteModel(
            name='RegistrationFormC',
        ),
    ]
