# Generated by Django 4.1.3 on 2024-09-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0184_answersheet_created_at2_answersheet_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationreceipt',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='registrationreceipt',
            name='user',
        ),
        migrations.RenameField(
            model_name='answersheet',
            old_name='created_at2',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='answersheet',
            old_name='user2',
            new_name='user',
        ),
    ]
