# Generated by Django 4.1.3 on 2024-09-26 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fsm', '0186_alter_answersheet_created_at_alter_answersheet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_sheets', to='fsm.registrationform'),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_sheets', to=settings.AUTH_USER_MODEL),
        ),
    ]
