# Generated by Django 4.1.3 on 2024-09-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0188_remove_edge_cost_object_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='name',
        ),
        migrations.AddField(
            model_name='object',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
