# Generated by Django 4.1.3 on 2024-10-05 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0191_boxwidget_alter_widget_widget_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoxWidget',
            new_name='Placeholder',
        ),
    ]
