# Generated by Django 4.1.3 on 2024-10-08 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0193_alter_widget_widget_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='creator',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fsm',
            name='_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_fsm', to='fsm.object'),
        ),
        migrations.CreateModel(
            name='State2',
            fields=[
                ('object_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fsm.object')),
                ('template', models.CharField(choices=[('normal', 'Normal'), ('board', 'Board')], default='normal', max_length=20)),
                ('show_appbar', models.BooleanField(default=True)),
                ('is_end', models.BooleanField(default=False)),
                ('fsm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states2', to='fsm.fsm')),
                ('papers', models.ManyToManyField(default=list, to='fsm.paper')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('fsm.object',),
        ),
        migrations.AddField(
            model_name='edge',
            name='head2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inward_edges', to='fsm.state2'),
        ),
        migrations.AddField(
            model_name='edge',
            name='tail2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outward_edges', to='fsm.state2'),
        ),
        migrations.AddField(
            model_name='fsm',
            name='first_state2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_fsm', to='fsm.state2'),
        ),
        migrations.AddField(
            model_name='hint',
            name='reference2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='fsm.state2'),
        ),
        migrations.AddField(
            model_name='player',
            name='current_state2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='fsm.state2'),
        ),
        migrations.AddField(
            model_name='playerstatehistory',
            name='state2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_state_histories', to='fsm.state2'),
        ),
        migrations.AddField(
            model_name='playertransition',
            name='source_state2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_departure_transitions', to='fsm.state2'),
        ),
        migrations.AddField(
            model_name='playertransition',
            name='target_state2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_arrival_transitions', to='fsm.state2'),
        ),
    ]
