# Generated by Django 4.1.3 on 2024-10-08 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0194_object_creator_alter_fsm__object_state2_edge_head2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='head2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inward_edges', to='fsm.state2'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='tail2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outward_edges', to='fsm.state2'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='reference2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hints', to='fsm.state2'),
        ),
    ]
