# Generated by Django 4.1.3 on 2024-10-08 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0195_alter_edge_head2_alter_edge_tail2_and_more'),
    ]

    operations = [

        migrations.RenameModel(
            old_name='State',
            new_name='Statec',
        ),
        migrations.RenameModel(
            old_name='State2',
            new_name='State',
        ),

        migrations.RenameField(
            model_name='player',
            old_name='current_state',
            new_name='current_statec',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='current_state2',
            new_name='current_state',
        ),


        migrations.RenameField(
            model_name='fsm',
            old_name='first_state',
            new_name='first_statec',
        ),
        migrations.RenameField(
            model_name='fsm',
            old_name='first_state2',
            new_name='first_state',
        ),


        migrations.RenameField(
            model_name='edge',
            old_name='head',
            new_name='headc',
        ),
        migrations.RenameField(
            model_name='edge',
            old_name='head2',
            new_name='head',
        ),
        migrations.RenameField(
            model_name='edge',
            old_name='tail',
            new_name='tailc',
        ),
        migrations.RenameField(
            model_name='edge',
            old_name='tail2',
            new_name='tail',
        ),


        migrations.RenameField(
            model_name='playertransition',
            old_name='source_state',
            new_name='source_statec',
        ),
        migrations.RenameField(
            model_name='playertransition',
            old_name='source_state2',
            new_name='source_state',
        ),
        migrations.RenameField(
            model_name='playertransition',
            old_name='target_state',
            new_name='target_statec',
        ),
        migrations.RenameField(
            model_name='playertransition',
            old_name='target_state2',
            new_name='target_state',
        ),


        migrations.RenameField(
            model_name='playerstatehistory',
            old_name='state',
            new_name='statec',
        ),
        migrations.RenameField(
            model_name='playerstatehistory',
            old_name='state2',
            new_name='state',
        ),


        migrations.RenameField(
            model_name='hint',
            old_name='reference',
            new_name='referencec',
        ),
        migrations.RenameField(
            model_name='hint',
            old_name='reference2',
            new_name='reference',
        ),

    ]
