# Generated by Django 4.1.3 on 2024-10-08 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0197_alter_edge_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='template',
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_type',
            field=models.CharField(choices=[('RegistrationForm', 'Registrationform'), ('State', 'State'), ('Hint', 'Hint'), ('WidgetHint', 'Widgethint'), ('Article', 'Article'), ('General', 'General')], default='General', max_length=25),
        ),
        migrations.AlterField(
            model_name='state',
            name='fsm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='fsm.fsm'),
        ),
        migrations.AlterField(
            model_name='statec',
            name='fsm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statesc', to='fsm.fsm'),
        ),
    ]
