# Generated by Django 4.1.3 on 2024-10-08 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0198_remove_paper_template_alter_paper_paper_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='headc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inward_edges', to='fsm.statec'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='tailc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outward_edges', to='fsm.statec'),
        ),
    ]
