# Generated by Django 4.1.3 on 2024-10-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0199_alter_edge_headc_alter_edge_tailc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='papers',
            field=models.ManyToManyField(default=list, related_name='states', to='fsm.paper'),
        ),
    ]
