# Generated by Django 4.1.3 on 2024-10-08 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0200_alter_state_papers'),
    ]

    operations = [

    ]
