# Generated by Django 4.1.3 on 2024-10-08 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0200_alter_state_papers'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatePaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fsm.paper')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fsm.state')),
            ],
        ),
    ]
