# Generated by Django 4.1.3 on 2024-10-08 11:20

from django.db import migrations, models


def preserve_m2m_data(apps, schema_editor):
    State = apps.get_model('fsm', 'State')
    StatePaper = apps.get_model('fsm', 'StatePaper')
    for state in State.objects.all():
        for i, paper in enumerate(state.papers.all()):
            StatePaper.objects.create(state=state, paper=paper, order=i)


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0201_statepaper'),
    ]

    operations = [
        migrations.RunPython(preserve_m2m_data),
        migrations.RemoveField(
            model_name='state',
            name='papers',
        ),
    ]
