# Generated by Django 4.1.3 on 2024-10-08 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0203_state_papers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inward_edges', to='fsm.state'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='tail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outward_edges', to='fsm.state'),
        ),
    ]
