# Generated by Django 4.1.3 on 2024-10-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0204_alter_edge_head_alter_edge_tail'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
