# Generated by Django 4.1.3 on 2024-10-11 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0205_object_website'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statepaper',
            unique_together={('paper', 'state')},
        ),
    ]
