# Generated by Django 4.1.3 on 2024-10-13 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0206_alter_statepaper_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions2', to='fsm.object')),
            ],
        ),
    ]
