# Generated by Django 4.1.3 on 2024-10-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0207_position2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Position',
            new_name='Positionc',
        ),
        migrations.RenameModel(
            old_name='Position2',
            new_name='Position',
        ),
    ]
