# Generated by Django 4.1.3 on 2024-10-13 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0208_rename_position2_position22'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='fsm.object'),
        ),
        migrations.AlterField(
            model_name='positionc',
            name='object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='positionc', serialize=False, to='fsm.object'),
        ),
    ]
