# Generated by Django 4.1.3 on 2024-10-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0210_delete_positionc'),
    ]

    operations = [
        migrations.AddField(
            model_name='statec',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
