# Generated by Django 4.1.3 on 2024-10-18 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0212_remove_edge_headc_remove_edge_tailc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multichoiceproblem',
            old_name='maximum_choices_could_be_chosen',
            new_name='max_selections',
        ),
        migrations.AddField(
            model_name='multichoiceproblem',
            name='lock_after_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multichoiceproblem',
            name='min_selections',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(0)]),
        ),
    ]
