# Generated by Django 4.1.3 on 2024-10-18 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0213_rename_maximum_choices_could_be_chosen_multichoiceproblem_max_selections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multichoiceproblem',
            name='min_selections',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
