# Generated by Django 4.1.3 on 2024-10-18 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0214_alter_multichoiceproblem_min_selections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsm',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fsms', to='fsm.program'),
        ),
    ]
