# Generated by Django 4.1.3 on 2024-10-21 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0215_alter_fsm_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_sheets', to='fsm.form'),
        ),
    ]
