# Generated by Django 4.1.3 on 2024-10-21 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0216_alter_answersheet_form'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='player',
            name='_answer_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fsm.answersheet'),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answer_sheets', to='fsm.form'),
        ),
    ]
