# Generated by Django 4.1.3 on 2024-10-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0217_alter_player_unique_together_player__answer_sheet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='text',
        ),
        migrations.AddField(
            model_name='player',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
