# Generated by Django 4.1.3 on 2024-10-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0218_remove_edge_text_player_finished_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
