# Generated by Django 4.1.3 on 2024-10-28 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0219_alter_player_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='fsm.registrationreceipt'),
        ),
    ]
