# Generated by Django 4.1.3 on 2024-11-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0221_audio_autoplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='multichoiceproblem',
            name='randomize_choices',
            field=models.BooleanField(default=False, help_text='If enabled, the choices will be presented in random order'),
        ),
    ]
