# Generated by Django 4.1.3 on 2024-11-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0222_multichoiceproblem_randomize_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsm',
            name='participant_limit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
