# Generated by Django 4.1.3 on 2024-11-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0224_rename_lock_after_answer_multichoiceproblem_disable_after_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audio',
            name='volume',
            field=models.IntegerField(default=100),
        ),
    ]
