# Generated by Django 4.1.3 on 2024-11-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0225_audio_repeat_audio_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcontactinfo',
            name='rubika_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
