# Generated by Django 4.1.3 on 2024-11-10 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0226_programcontactinfo_rubika_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralHint',
            fields=[
                ('object_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fsm.object')),
                ('hint_content', models.ForeignKey(blank=True, help_text='The content of the hint, which can be a Paper or other related material.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fsm.paper')),
                ('target_object', models.ForeignKey(help_text='The object (e.g., question, lesson) this hint is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='general_hints', to='fsm.object')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('fsm.object',),
        ),
    ]
