# Generated by Django 4.1.3 on 2024-11-10 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0227_generalhint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('object_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fsm.object')),
                ('type', models.CharField(help_text='Type of resource (e.g., Hint, Document, Evidences, etc.)', max_length=30)),
                ('content', models.JSONField(blank=True, help_text='The content of the resource, which can be a PaperId or other related material.', null=True)),
                ('target_object', models.ForeignKey(help_text='The object (e.g., question, lesson) this resource is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='fsm.object')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('fsm.object',),
        ),
    ]
