# Generated by Django 4.1.3 on 2024-11-10 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0228_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='target_object',
            field=models.ForeignKey(blank=True, help_text='The object (e.g., question, lesson) this resource is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='fsm.object'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(help_text='Type of resource (e.g., hint, document, evidence, book, etc.)', max_length=30),
        ),
    ]
