# Generated by Django 4.1.3 on 2024-11-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0229_alter_resource_target_object_alter_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsm',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in minutes. 0 means unlimited.'),
        ),
    ]
