# Generated by Django 4.1.3 on 2024-11-16 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0230_fsm_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='created_at',
            new_name='started_at',
        ),
    ]
