# Generated by Django 4.1.3 on 2024-11-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0231_rename_created_at_player_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('Iframe', 'Iframe'), ('Video', 'Video'), ('Image', 'Image'), ('Aparat', 'Aparat'), ('Audio', 'Audio'), ('TextWidget', 'Textwidget'), ('Placeholder', 'Placeholder'), ('DetailBoxWidget', 'Detailboxwidget'), ('SmallAnswerProblem', 'Smallanswerproblem'), ('BigAnswerProblem', 'Biganswerproblem'), ('MultiChoiceProblem', 'Multichoiceproblem'), ('UploadFileProblem', 'Uploadfileproblem'), ('ButtonWidget', 'Buttonwidget'), ('RandomWidget', 'Randomwidget')], max_length=30),
        ),
    ]
