# Generated by Django 4.1.3 on 2024-11-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0232_alter_widget_widget_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='participant_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
