# Generated by Django 4.1.3 on 2024-12-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0233_form_participant_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper_type',
            field=models.CharField(choices=[('RegistrationForm', 'Registrationform'), ('Hint', 'Hint'), ('WidgetHint', 'Widgethint'), ('Article', 'Article'), ('General', 'General')], default='General', max_length=25),
        ),
    ]
