# Generated by Django 4.1.3 on 2024-12-14 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0234_alter_paper_paper_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biganswer',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='fsm.biganswerproblem'),
        ),
        migrations.AlterField(
            model_name='smallanswer',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='fsm.smallanswerproblem'),
        ),
        migrations.AlterField(
            model_name='uploadfileanswer',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='fsm.uploadfileproblem'),
        ),
    ]
