# Generated by Django 4.1.3 on 2025-01-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0235_alter_biganswer_problem_alter_smallanswer_problem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsm',
            name='participant_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
