# Generated by Django 4.1.3 on 2025-01-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0236_alter_fsm_participant_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='background_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
