# Generated by Django 4.1.3 on 2025-01-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0237_form_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(condition=models.Q(('finished_at__isnull', True)), fields=('user', 'fsm'), name='unique_active_player'),
        ),
    ]
