# Generated by Django 4.1.3 on 2025-02-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0238_alter_player_last_visit_player_unique_active_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='new_cover_page',
            field=models.URLField(blank=True, null=True),
        ),
    ]
