# Generated by Django 4.1.3 on 2025-02-02 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0239_article_new_cover_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cover_page',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='article',
            name='publisher',
        ),
    ]
