# Generated by Django 4.1.3 on 2025-02-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0240_remove_article_cover_page_remove_article_is_draft_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='new_cover_page',
            new_name='cover_image',
        ),
    ]
