# Generated by Django 4.1.3 on 2025-02-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0241_rename_new_cover_page_article_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='fsm.tag'),
        ),
    ]
