# Generated by Django 4.1.3 on 2025-02-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0242_alter_article_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fsm',
            old_name='cover_page',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='cover_page',
            new_name='cover_image',
        ),
    ]
