# Generated by Django 5.1 on 2025-03-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0243_rename_cover_page_fsm_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsm',
            name='show_player_performance_on_end',
            field=models.BooleanField(default=False, help_text="If enabled, the player's performance analysis will be shown to them after completing the FSM."),
        ),
    ]
