# Generated by Django 5.1 on 2025-04-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0244_fsm_show_player_performance_on_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsm',
            name='mentors2',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
