# Generated by Django 5.1 on 2025-04-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0245_fsm_mentors2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fsm',
            name='mentors',
        ),
        migrations.RenameField(
            model_name='fsm',
            old_name='mentors2',
            new_name='mentors',
        ),
    ]
