# Generated by Django 5.1 on 2025-04-27 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0246_remove_fsm_mentors2_remove_fsm_mentors_fsm_mentors'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_program', to='fsm.fsm'),
        ),
    ]
