# Generated by Django 5.1 on 2025-05-08 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0247_program_menu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={},
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['tail', 'head'], name='idx_edge_tail_head'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['head'], name='idx_edge_head'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['tail'], name='idx_edge_tail'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['user', 'fsm', 'finished_at'], name='idx_player_user_fsm_finished'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['fsm'], name='idx_player_fsm'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['user'], name='idx_player_user'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['current_state'], name='idx_player_current_state'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['fsm'], name='state_fsm_idx'),
        ),
        migrations.AddIndex(
            model_name='statepaper',
            index=models.Index(fields=['state', 'paper'], name='idx_statepaper_state_paper'),
        ),
        migrations.AddIndex(
            model_name='statepaper',
            index=models.Index(fields=['state', 'order'], name='idx_statepaper_state_order'),
        ),
    ]
