# Generated by Django 5.1 on 2025-05-08 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fsm', '0248_alter_state_options_edge_idx_edge_tail_head_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='answersheet',
            options={},
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['submitted_by'], name='idx_ans_submitted_by'),
        ),
        migrations.AddIndex(
            model_name='answersheet',
            index=models.Index(fields=['user'], name='idx_sheet_user'),
        ),
    ]
