# Generated by Django 5.1 on 2025-05-08 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fsm', '0249_alter_answer_options_alter_answersheet_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationreceipt',
            options={},
        ),
        migrations.AddIndex(
            model_name='answersheet',
            index=models.Index(fields=['user', 'form'], name='idx_sheet_user_form'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['fsm', 'user'], name='idx_player_fsm_user'),
        ),
        migrations.AddIndex(
            model_name='playerstatehistory',
            index=models.Index(fields=['player', 'state', 'departure'], name='idx_psh_player_state_dep'),
        ),
        migrations.AddIndex(
            model_name='registrationreceipt',
            index=models.Index(fields=['is_participating'], name='idx_rr_participating'),
        ),
    ]
