# Generated by Django 5.1 on 2025-05-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0250_alter_registrationreceipt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertransition',
            name='is_backward',
            field=models.BooleanField(default=False),
        ),
    ]
