# Generated by Django 5.1 on 2025-05-24 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0252_alter_playertransition_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertransition',
            name='reverted_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverts', to='fsm.playertransition'),
        ),
    ]
