# Generated by Django 5.1 on 2025-05-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0253_playertransition_reverted_by'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='playertransition',
            index=models.Index(fields=['player', 'time'], name='fsm_playert_player__fb5bdb_idx'),
        ),
        migrations.AddIndex(
            model_name='playertransition',
            index=models.Index(fields=['player', 'target_state', 'is_backward', 'reverted_by', 'time'], name='pt_tgt_bw_rev_time_ix'),
        ),
    ]
