# Generated by Django 5.1 on 2025-06-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0254_playertransition_fsm_playert_player__fb5bdb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='max_registrants',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of registrants allowed. Null means no limit.', null=True),
        ),
    ]
