# Generated by Django 5.1 on 2025-06-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0255_registrationform_max_registrants'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcontactinfo',
            name='whatsapp_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='programcontactinfo',
            name='bale_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='programcontactinfo',
            name='eitaa_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='programcontactinfo',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='programcontactinfo',
            name='rubika_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='programcontactinfo',
            name='shad_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='programcontactinfo',
            name='telegram_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
