# Generated by Django 5.1 on 2025-06-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0256_programcontactinfo_whatsapp_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='maximum_participant',
        ),
    ]
