# Generated by Django 5.1 on 2025-06-04 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0257_remove_program_maximum_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playertransition',
            name='transited_edge',
        ),
        migrations.DeleteModel(
            name='PlayerStateHistory',
        ),
    ]
