# Generated by Django 4.1.3 on 2024-10-20 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fsm', '0215_alter_fsm_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.UUIDField()),
                ('fund', models.JSONField()),
                ('spent_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.IntegerField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fsm.object')),
            ],
            options={
                'ordering': ['-spent_at'],
            },
        ),
    ]
