# Generated by Django 4.1.3 on 2024-10-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='object',
            field=models.IntegerField(),
        ),
    ]
