# Generated by Django 4.1.3 on 2024-11-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_spend_object'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spend',
        ),
    ]
