# Generated by Django 4.1.3 on 2024-03-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteappearance', '0003_alter_banner_banner_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
