# Generated by Django 5.1 on 2025-03-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField(max_length=100)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('play', 'Play'), ('pause', 'Pause'), ('progress', 'Progress'), ('seeking', 'Seeking'), ('completed', 'Completed')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
