# Generated by Django 5.1 on 2025-04-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Content Log', 'verbose_name_plural': 'Content Logs'},
        ),
    ]
