# Generated by Django 4.1.3 on 2024-11-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.UUIDField()),
                ('object_id', models.IntegerField()),
                ('fund', models.JSONField()),
                ('spent_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-spent_at'],
            },
        ),
    ]
