# Generated by Django 4.1.3 on 2024-08-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0003_alter_intrinsicattribute_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performableaction',
            name='type',
            field=models.CharField(choices=[('see', 'See'), ('purchase', 'Purchase'), ('sell', 'Sell'), ('copy', 'Copy'), ('assess_answer', 'Assess Answer'), ('solve', 'Solve'), ('submit', 'Submit'), ('enter', 'Enter'), ('transit', 'Transit')], max_length=20),
        ),
    ]
