# Generated by Django 4.1.3 on 2024-10-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0005_condition_transition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
