# Generated by Django 4.1.3 on 2024-10-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0006_attribute_order_alter_attribute_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='name',
            new_name='title',
        ),
    ]
