# Generated by Django 4.1.3 on 2024-10-23 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0008_reward_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('performableaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attributes.performableaction')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('attributes.performableaction',),
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('intrinsicattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attributes.intrinsicattribute')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('attributes.intrinsicattribute',),
        ),
        migrations.CreateModel(
            name='Enabled',
            fields=[
                ('intrinsicattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attributes.intrinsicattribute')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('attributes.intrinsicattribute',),
        ),
    ]
