# Generated by Django 4.1.3 on 2024-10-23 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0009_buy_cost_enabled'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cost',
            new_name='Funds',
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
