# Generated by Django 4.1.3 on 2024-11-16 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0013_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('performableaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attributes.performableaction')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('attributes.performableaction',),
        ),
        migrations.CreateModel(
            name='Rewarding',
            fields=[
                ('performableaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attributes.performableaction')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('attributes.performableaction',),
        ),
    ]
