# Generated by Django 5.1 on 2025-05-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0015_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='is_backward',
            field=models.BooleanField(default=False, help_text='When True, indicates this Transition should be treated as a ‘backward’‐type move.'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='destination_state_id',
            field=models.IntegerField(blank=True, help_text='If NULL, this Transition transit the player to its previous state.  If not NULL, it transit it to that state (and flags itself as a ‘backward’ transition).', null=True),
        ),
    ]
